export enum RealtimeTopicId {
  GRAPHQL = "9",
  SKYWALKER = "88",
  SEND_MESSAGE = "132",
  SEND_MESSAGE_RESPONSE = "133",
  IRIS_SUB = "134",
  IRIS_SUB_RESPONSE = "135",
  MESSAGE_SYNC = "146",
  REALTIME_SUB = "149",
  REGION_HINT = "150",
  FOREGROUND_STATE = "151",
  BACKGROUND_STATE = "152",
}
