/**
 * This file was generated by scripts/gen-openapi.ts
 * Do not edit this file manually.
 */

/* eslint-disable */
/* prettier-ignore */

export interface paths {
    "/apps/{1}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header: {
                    "x-ig-app-locale": string;
                    "x-ig-device-locale": string;
                    "x-ig-mapped-locale": string;
                    "x-pigeon-session-id": string;
                    "x-pigeon-rawclienttime": string;
                    "x-ig-bandwidth-speed-kbps": string;
                    "x-ig-bandwidth-totalbytes-b": string;
                    "x-ig-bandwidth-totaltime-ms": string;
                    "x-bloks-version-id": string;
                    "x-ig-www-claim": string;
                    "x-bloks-prism-button-version": string;
                    "x-bloks-prism-colors-enabled": string;
                    "x-bloks-prism-ax-base-colors-enabled": string;
                    "x-bloks-prism-font-enabled": string;
                    "x-bloks-is-layout-rtl": string;
                    "x-ig-device-id": string;
                    "x-ig-family-device-id": string;
                    "x-ig-android-id": string;
                    "x-ig-timezone-offset": string;
                    "x-fb-connection-type": string;
                    "x-ig-connection-type": string;
                    "x-ig-capabilities": string;
                    "x-ig-app-id": string;
                    priority?: string;
                    "x-tigon-is-retry"?: string;
                    "user-agent": string;
                    "accept-language"?: string;
                    "x-mid": string;
                    "ig-intended-user-id": string;
                    "content-type"?: string;
                    "accept-encoding"?: string;
                    "x-fb-http-engine": string;
                    "x-fb-client-ip": string;
                    "x-fb-server-cluster": string;
                    "x-ig-nav-chain"?: string;
                    "x-ig-attest-params"?: string;
                };
                path: {
                    1: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        params: string;
                        bk_client_context: string;
                        bloks_versioning_id: string;
                    };
                };
            };
            responses: never;
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
