/**
 * This file was generated by scripts/gen-openapi.ts
 * Do not edit this file manually.
 */

/* eslint-disable */
/* prettier-ignore */

export interface paths {
    "/v1/zr/dual_tokens/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header: {
                    "x-ig-app-locale": string;
                    "x-ig-device-locale": string;
                    "x-ig-mapped-locale": string;
                    "x-pigeon-rawclienttime": string;
                    "x-ig-bandwidth-speed-kbps": string;
                    "x-ig-bandwidth-totalbytes-b": string;
                    "x-ig-bandwidth-totaltime-ms": string;
                    "x-bloks-version-id": string;
                    "x-ig-www-claim": string;
                    "x-bloks-prism-button-version": string;
                    "x-bloks-prism-colors-enabled": string;
                    "x-bloks-prism-ax-base-colors-enabled": string;
                    "x-bloks-prism-font-enabled": string;
                    "x-bloks-is-layout-rtl": string;
                    "x-ig-device-id": string;
                    "x-ig-family-device-id"?: string;
                    "x-ig-android-id": string;
                    "x-ig-timezone-offset": string;
                    "x-ig-nav-chain"?: string;
                    "x-fb-session-id"?: string;
                    "x-fb-session-private"?: string;
                    "x-fb-connection-type": string;
                    "x-ig-connection-type": string;
                    "x-fb-network-properties"?: string;
                    "x-ig-capabilities": string;
                    "x-ig-app-id": string;
                    "user-agent": string;
                    "accept-language"?: string;
                    "x-mid"?: string;
                    "ig-intended-user-id": string;
                    "content-type"?: string;
                    "accept-encoding"?: string;
                    "x-fb-http-engine": string;
                    "x-fb-client-ip": string;
                    "x-fb-server-cluster": string;
                    "x-pigeon-session-id"?: string;
                    priority?: string;
                    authorization?: string;
                    "ig-u-ds-user-id"?: string;
                    "ig-u-rur"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        normal_token_hash: string;
                        device_id: string;
                        _uuid: string;
                        custom_device_id: string;
                        fetch_reason: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        "content-type"?: string;
                        date: string;
                        vary?: string;
                        "content-language": string;
                        "strict-transport-security"?: string;
                        "cache-control"?: string;
                        pragma?: string;
                        expires?: string;
                        "x-frame-options": string;
                        "content-security-policy": string;
                        "cross-origin-embedder-policy-report-only": string;
                        "report-to": string;
                        "cross-origin-opener-policy": string;
                        "x-content-type-options": string;
                        "x-xss-protection": string;
                        "x-ig-push-state": string;
                        "x-ig-cache-control": string;
                        "x-aed": string;
                        "x-ig-request-elapsed-time-ms": string;
                        "x-ig-peak-v2": string;
                        "x-ig-peak-time": string;
                        "x-ig-capacity-level": string;
                        "content-encoding": string;
                        "x-stack": string;
                        "ig-set-ig-u-ig-direct-region-hint": string;
                        "ig-set-ig-u-shbid": string;
                        "ig-set-ig-u-shbts": string;
                        "ig-set-ig-u-rur": string;
                        "ig-set-ig-u-ds-user-id": string;
                        "x-perf-stats": string;
                        "x-ig-origin-region": string;
                        "x-fb-client-ip-forwarded": string;
                        "x-fb-server-cluster-forwarded": string;
                        "alt-svc": string;
                        "x-fb-connection-quality": string;
                        "ig-set-x-mid"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            normal_token: {
                                carrier_name: string;
                                carrier_id: number;
                                ttl: number;
                                features: null[];
                                request_time: number;
                                token_hash: string;
                                rewrite_rules: null[];
                                enabled_wallet_defs_keys: null[];
                                deadline: string;
                                zero_cms_fetch_interval_seconds: number;
                                carrier_signal_config: null[];
                                eligibility_hash: string;
                            };
                            free_token: {
                                carrier_name: string;
                                carrier_id: number;
                                ttl: number;
                                features: null[];
                                request_time: number;
                                token_hash: string;
                                rewrite_rules: null[];
                                enabled_wallet_defs_keys: null[];
                                deadline: string;
                                zero_cms_fetch_interval_seconds: number;
                                carrier_signal_config: null[];
                                eligibility_hash: string;
                            };
                            status: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/attestation/create_android_keystore/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header: {
                    "x-ig-app-locale": string;
                    "x-ig-device-locale": string;
                    "x-ig-mapped-locale": string;
                    "x-pigeon-rawclienttime": string;
                    "x-ig-bandwidth-speed-kbps": string;
                    "x-ig-bandwidth-totalbytes-b": string;
                    "x-ig-bandwidth-totaltime-ms": string;
                    "x-bloks-version-id": string;
                    "x-ig-www-claim": string;
                    "x-bloks-prism-button-version": string;
                    "x-bloks-prism-colors-enabled": string;
                    "x-bloks-prism-ax-base-colors-enabled": string;
                    "x-bloks-prism-font-enabled": string;
                    "x-bloks-is-layout-rtl": string;
                    "x-ig-device-id": string;
                    "x-ig-family-device-id"?: string;
                    "x-ig-android-id": string;
                    "x-ig-timezone-offset": string;
                    "x-ig-nav-chain"?: string;
                    "x-fb-session-id"?: string;
                    "x-fb-session-private"?: string;
                    "x-fb-connection-type": string;
                    "x-ig-connection-type": string;
                    "x-fb-network-properties"?: string;
                    "x-ig-capabilities": string;
                    "x-ig-app-id": string;
                    "user-agent": string;
                    "accept-language"?: string;
                    "x-mid"?: string;
                    "ig-intended-user-id": string;
                    "content-type"?: string;
                    "accept-encoding"?: string;
                    "x-fb-http-engine": string;
                    "x-fb-client-ip": string;
                    "x-fb-server-cluster": string;
                    "x-pigeon-session-id"?: string;
                    priority?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        app_scoped_device_id: string;
                        key_hash: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        "content-type"?: string;
                        date: string;
                        vary?: string;
                        "content-language": string;
                        "strict-transport-security"?: string;
                        "cache-control"?: string;
                        pragma?: string;
                        expires?: string;
                        "x-frame-options": string;
                        "content-security-policy": string;
                        "cross-origin-embedder-policy-report-only": string;
                        "report-to": string;
                        "cross-origin-opener-policy": string;
                        "x-content-type-options": string;
                        "x-xss-protection": string;
                        "x-ig-push-state": string;
                        "x-ig-cache-control": string;
                        "x-aed": string;
                        "x-ig-request-elapsed-time-ms": string;
                        "x-ig-peak-v2": string;
                        "x-ig-peak-time": string;
                        "x-ig-capacity-level": string;
                        "x-stack": string;
                        "ig-set-ig-u-ig-direct-region-hint": string;
                        "ig-set-ig-u-shbid": string;
                        "ig-set-ig-u-shbts": string;
                        "ig-set-ig-u-rur": string;
                        "ig-set-ig-u-ds-user-id": string;
                        "x-perf-stats": string;
                        "x-ig-origin-region": string;
                        "x-fb-client-ip-forwarded": string;
                        "x-fb-server-cluster-forwarded": string;
                        "alt-svc": string;
                        "x-fb-connection-quality": string;
                        "ig-set-x-mid"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            challenge_nonce: string;
                            key_nonce: string;
                            status: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/multiple_accounts/get_account_family/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    request_source: string;
                };
                header: {
                    "x-ig-app-locale": string;
                    "x-ig-device-locale": string;
                    "x-ig-mapped-locale": string;
                    "x-pigeon-rawclienttime": string;
                    "x-ig-bandwidth-speed-kbps": string;
                    "x-ig-bandwidth-totalbytes-b": string;
                    "x-ig-bandwidth-totaltime-ms": string;
                    "x-bloks-version-id": string;
                    "x-ig-www-claim": string;
                    "x-bloks-prism-button-version": string;
                    "x-bloks-prism-colors-enabled": string;
                    "x-bloks-prism-ax-base-colors-enabled": string;
                    "x-bloks-prism-font-enabled": string;
                    "x-bloks-is-layout-rtl": string;
                    "x-ig-device-id": string;
                    "x-ig-family-device-id": string;
                    "x-ig-android-id": string;
                    "x-ig-timezone-offset": string;
                    "x-ig-nav-chain": string;
                    "x-fb-connection-type": string;
                    "x-ig-connection-type": string;
                    "x-ig-capabilities": string;
                    "x-ig-app-id": string;
                    priority?: string;
                    "user-agent": string;
                    "accept-language"?: string;
                    authorization: string;
                    "x-mid": string;
                    "ig-u-ds-user-id": string;
                    "ig-u-rur": string;
                    "ig-intended-user-id": string;
                    "accept-encoding"?: string;
                    "x-fb-http-engine": string;
                    "x-fb-client-ip": string;
                    "x-fb-server-cluster": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        "content-type"?: string;
                        date: string;
                        vary?: string;
                        "content-language": string;
                        "strict-transport-security"?: string;
                        "cache-control"?: string;
                        pragma?: string;
                        expires?: string;
                        "x-frame-options": string;
                        "content-security-policy": string;
                        "cross-origin-embedder-policy-report-only": string;
                        "report-to": string;
                        "cross-origin-opener-policy": string;
                        "x-content-type-options": string;
                        "x-xss-protection": string;
                        "x-ig-push-state": string;
                        "x-ig-cache-control": string;
                        "x-aed": string;
                        "x-ig-request-elapsed-time-ms": string;
                        "x-ig-peak-v2": string;
                        "x-ig-peak-time": string;
                        "x-ig-capacity-level": string;
                        "content-encoding": string;
                        "x-stack": string;
                        "ig-set-ig-u-ig-direct-region-hint": string;
                        "ig-set-ig-u-shbid": string;
                        "ig-set-ig-u-shbts": string;
                        "ig-set-ig-u-rur": string;
                        "ig-set-ig-u-ds-user-id": string;
                        "x-perf-stats": string;
                        "x-ig-origin-region": string;
                        "x-fb-client-ip-forwarded": string;
                        "x-fb-server-cluster-forwarded": string;
                        "alt-svc": string;
                        "x-fb-connection-quality": string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            child_accounts: null[];
                            main_accounts: null[];
                            current_account: {
                                pk: number;
                                pk_id: string;
                                full_name: string;
                                is_private: boolean;
                                has_onboarded_to_text_post_app: boolean;
                                strong_id__: string;
                                has_password: number;
                                id: string;
                                username: string;
                                is_verified: boolean;
                                profile_pic_id: string;
                                profile_pic_url: string;
                                has_onboarded_to_basel: boolean;
                            };
                            status: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
