import {
  type Flow2OpenAPIConfig,
  flows2OpenAPI,
} from "@instagramjs/flows2openapi";
import fs from "fs";
import openapiTS, { astToString, type OpenAPI3 } from "openapi-typescript";
import path from "path";
import yaml from "yaml";

const FLOWS_JSON_FILE = path.join(
  import.meta.dirname,
  "..",
  "..",
  "..",
  "reverse-engineering",
  "flows_json.out",
);
const BASE_OPENAPI_DIR = path.join(import.meta.dirname, "..", "openapi");
const BASE_SRC_DIR = path.join(import.meta.dirname, "..", "src");

type GeneratorConfig = {
  apiPrefix: string;
  openapiDir: string;
  srcDir: string;
  flowsConfig?: Partial<Flow2OpenAPIConfig>;
};

const GENERATOR_CONFIGS: GeneratorConfig[] = [
  {
    apiPrefix: "https://i.instagram.com/api",
    openapiDir: path.join(BASE_OPENAPI_DIR, "instagram"),
    srcDir: path.join(BASE_SRC_DIR, "instagram"),
    flowsConfig: {
      filterExample: () => false,
      filterResponse: () => true,
      filterSchema: ({ path }) => {
        if (
          path.endsWith("bloks_payload.layout") ||
          path.endsWith("bloks_payload.tree") ||
          path.endsWith("bloks_payload.templates") ||
          path.endsWith("bloks_payload.ft")
        ) {
          return false;
        }
        return true;
      },
    },
  },
  {
    apiPrefix: "https://graph.instagram.com",
    openapiDir: path.join(BASE_OPENAPI_DIR, "instagram-graph"),
    srcDir: path.join(BASE_SRC_DIR, "instagram-graph"),
    flowsConfig: {
      filterExample: () => false,
    },
  },
  {
    apiPrefix: "https://graph.facebook.com",
    openapiDir: path.join(BASE_OPENAPI_DIR, "facebook-graph"),
    srcDir: path.join(BASE_SRC_DIR, "facebook-graph"),
    flowsConfig: {
      filterExample: () => false,
    },
  },
];

const HEADER = `/**
 * This file was generated by scripts/gen-openapi.ts
 * Do not edit this file manually.
 */

/* eslint-disable */
/* prettier-ignore */

`;

async function generate(config: GeneratorConfig, jsonDump: string) {
  const openapiDefFile = path.join(config.openapiDir, "openapi.yaml");
  const openapiTsFile = path.join(config.srcDir, "schema.ts");

  await fs.promises.mkdir(config.openapiDir, { recursive: true });
  await fs.promises.mkdir(config.srcDir, { recursive: true });

  let existingDef: OpenAPI3 | null = null;
  try {
    existingDef = yaml.parse(
      await fs.promises.readFile(openapiDefFile, "utf-8"),
    );
  } catch {
    // ignore
  }

  const def = await flows2OpenAPI(jsonDump, existingDef, {
    apiPrefix: config.apiPrefix,
    ...config.flowsConfig,
  });

  await fs.promises.writeFile(openapiDefFile, yaml.stringify(def));

  const ast = await openapiTS(def);
  const schemaCode = astToString(ast);

  await fs.promises.writeFile(openapiTsFile, HEADER + schemaCode);
}

async function main() {
  try {
    await fs.promises.access(FLOWS_JSON_FILE, fs.constants.F_OK);
  } catch {
    console.error(`Flows JSON dump does not exist at ${FLOWS_JSON_FILE}`);
    process.exit(1);
  }
  const jsonDump = await fs.promises.readFile(FLOWS_JSON_FILE, "utf-8");

  await Promise.all(
    GENERATOR_CONFIGS.map((config) => generate(config, jsonDump)),
  );
}

main();
